module.exports = {
  apps: [
    {
      name: 'rabhan-auth-service',
      script: './backend/services/auth-service/src/server.ts',
      cwd: '/opt/rabhan',
      interpreter: 'node',
      interpreter_args: '--loader tsx',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        JWT_SECRET: process.env.JWT_SECRET || 'rabhan_jwt_secret_key_production_change_this',
        JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || 'rabhan_jwt_refresh_secret_production_change_this',
        DATABASE_URL: 'postgresql://rabhan_auth:secure_password_here@localhost:5432/rabhan_auth',
        REDIS_URL: 'redis://localhost:6379/0',
        LOG_LEVEL: 'info',
        SAMA_AUDIT_ENABLED: 'true',
        SAMA_COMPLIANCE_MODE: 'production'
      },
      max_memory_restart: '300M',
      error_file: '/var/log/rabhan/auth-service-error.log',
      out_file: '/var/log/rabhan/auth-service-out.log',
      log_file: '/var/log/rabhan/auth-service.log',
      time: true,
      autorestart: true,
      watch: false,
      max_restarts: 3,
      min_uptime: '10s'
    },
    {
      name: 'rabhan-user-service',
      script: './backend/services/user-service/src/server.ts',
      cwd: '/opt/rabhan',
      interpreter: 'node',
      interpreter_args: '--loader tsx',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
        JWT_SECRET: process.env.JWT_SECRET || 'rabhan_jwt_secret_key_production_change_this',
        DATABASE_HOST: 'localhost',
        DATABASE_PORT: 5432,
        DATABASE_NAME: 'rabhan_user',
        DATABASE_USER: 'rabhan_user',
        DATABASE_PASSWORD: 'secure_password_here',
        REDIS_URL: 'redis://localhost:6379/1',
        AUTH_SERVICE_URL: 'http://localhost:3001/api/auth',
        LOG_LEVEL: 'info',
        SAMA_AUDIT_ENABLED: 'true',
        SAMA_COMPLIANCE_MODE: 'production'
      },
      max_memory_restart: '250M',
      error_file: '/var/log/rabhan/user-service-error.log',
      out_file: '/var/log/rabhan/user-service-out.log',
      log_file: '/var/log/rabhan/user-service.log',
      time: true,
      autorestart: true,
      watch: false,
      max_restarts: 3,
      min_uptime: '10s'
    },
    {
      name: 'rabhan-document-service',
      script: './backend/services/document-service/src/server.ts',
      cwd: '/opt/rabhan',
      interpreter: 'node',
      interpreter_args: '--loader tsx',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
        JWT_SECRET: process.env.JWT_SECRET || 'rabhan_jwt_secret_key_production_change_this',
        DATABASE_HOST: 'localhost',
        DATABASE_PORT: 5432,
        DATABASE_NAME: 'rabhan_documents',
        DATABASE_USER: 'rabhan_documents',
        DATABASE_PASSWORD: 'secure_password_here',
        REDIS_URL: 'redis://localhost:6379/2',
        AUTH_SERVICE_URL: 'http://localhost:3001/api/auth',
        UPLOAD_PATH: '/opt/rabhan/uploads',
        MAX_FILE_SIZE: '10485760',
        LOG_LEVEL: 'info',
        SAMA_AUDIT_ENABLED: 'true',
        SAMA_COMPLIANCE_MODE: 'production'
      },
      max_memory_restart: '400M',
      error_file: '/var/log/rabhan/document-service-error.log',
      out_file: '/var/log/rabhan/document-service-out.log',
      log_file: '/var/log/rabhan/document-service.log',
      time: true,
      autorestart: true,
      watch: false,
      max_restarts: 3,
      min_uptime: '10s'
    },
    {
      name: 'rabhan-contractor-service',
      script: './backend/services/contractor-service/src/server.ts',
      cwd: '/opt/rabhan',
      interpreter: 'node',
      interpreter_args: '--loader tsx',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
        JWT_SECRET: process.env.JWT_SECRET || 'rabhan_jwt_secret_key_production_change_this',
        DATABASE_HOST: 'localhost',
        DATABASE_PORT: 5432,
        DATABASE_NAME: 'rabhan_contractors',
        DATABASE_USER: 'rabhan_contractors',
        DATABASE_PASSWORD: 'secure_password_here',
        REDIS_URL: 'redis://localhost:6379/3',
        AUTH_SERVICE_URL: 'http://localhost:3001/api/auth',
        USER_SERVICE_URL: 'http://localhost:3002',
        DOCUMENT_SERVICE_URL: 'http://localhost:3003',
        LOG_LEVEL: 'info',
        SAMA_AUDIT_ENABLED: 'true',
        SAMA_COMPLIANCE_MODE: 'production'
      },
      max_memory_restart: '250M',
      error_file: '/var/log/rabhan/contractor-service-error.log',
      out_file: '/var/log/rabhan/contractor-service-out.log',
      log_file: '/var/log/rabhan/contractor-service.log',
      time: true,
      autorestart: true,
      watch: false,
      max_restarts: 3,
      min_uptime: '10s'
    },
    {
      name: 'rabhan-solar-calculator',
      script: './backend/services/solar-calculator-service/src/server.ts',
      cwd: '/opt/rabhan',
      interpreter: 'node',
      interpreter_args: '--loader tsx',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3005,
        JWT_SECRET: process.env.JWT_SECRET || 'rabhan_jwt_secret_key_production_change_this',
        LOG_LEVEL: 'info',
        SAMA_AUDIT_ENABLED: 'true',
        SAMA_COMPLIANCE_MODE: 'production'
      },
      max_memory_restart: '200M',
      error_file: '/var/log/rabhan/solar-calculator-error.log',
      out_file: '/var/log/rabhan/solar-calculator-out.log',
      log_file: '/var/log/rabhan/solar-calculator.log',
      time: true,
      autorestart: true,
      watch: false,
      max_restarts: 3,
      min_uptime: '10s'
    }
  ]
};